### ISSUE TITLE
openai.error.AuthenticationError: <empty message>

### ISSUE THREAD

**Issue by fbaldassarri** [borge12/simple-chat#9]
Getting this error

```
~/simple-chat$ python simple-chat.py 
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/simple-chat/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/anaconda3/envs/simple-chat/lib/python3.10/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/home/user/anaconda3/envs/simple-chat/lib/python3.10/site-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/anaconda3/envs/simple-chat/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/anaconda3/envs/simple-chat/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/user/anaconda3/envs/simple-chat/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/user/simple-chat/simple-chat.py", line 136, in chat
    response = openai.ChatCompletion.create(
  File "/home/user/anaconda3/envs/simple-chat/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/user/anaconda3/envs/simple-chat/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/user/anaconda3/envs/simple-chat/lib/python3.10/site-packages/openai/api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/user/anaconda3/envs/simple-chat/lib/python3.10/site-packages/openai/api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "/home/user/anaconda3/envs/simple-chat/lib/python3.10/site-packages/openai/api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: <empty message>
```

**Comment by fbaldassarri** [comment]
Sorry, it seems that my key had some problem. Just generated a new one...
